In [1]:
import pandas as pd
import numpy as np

In [2]:
from tqdm import tqdm, tqdm_notebook

In [3]:
from pathlib import Path

In [4]:
from IPython.display import Image

In [5]:
import ipywidgets as widgets

In [6]:
import requests

In [7]:
DATASET_PATH = Path('agg/')
!ls {DATASET_PATH}

amusement_1st_1000.csv	      disgust_1st_ins_1000.csv
amusement_1st_ins_1000.csv    disgust_2nd_1000.csv
amusement_2nd_1000.csv	      disgust_3rd_1000.csv
amusement_3rd_1000.csv	      disgust_4th_2000.csv
amusement_4th_2000.csv	      disgust_5th_2000.csv
amusement_5th_2000.csv	      disgust_6th_3000.csv
amusement_6th_3000.csv	      excitement_1st_1000.csv
anger_1st_1000.csv	      excitement_1st_ins_1000.csv
anger_1st_ins_1000.csv	      excitement_2nd_1000.csv
anger_2nd_1000.csv	      excitement_3rd_1000.csv
anger_3rd_1000.csv	      excitement_4th_2000.csv
anger_4th_2000.csv	      excitement_5th_2000.csv
anger_5th_2000.csv	      excitement_6th_3000.csv
anger_6th_3000.csv	      fear_1st_1000.csv
awe_1st_1000.csv	      fear_1st_ins_1000.csv
awe_1st_ins_1000.csv	      fear_2nd_1000.csv
awe_2nd_1000.csv	      fear_3rd_1000.csv
awe_3rd_1000.csv	      fear_4th_2000.csv
awe_4th_2000.csv	      fear_5th_2000.csv
awe_5th_2000.csv	      fear_6th_3000.csv
awe_6th_3000.csv	      fear_7th_2000.csv
contentment_1st_1000.csv      sadness_1st_1000.csv
contentment_1st_ins_1000.csv  sadness_1st_ins_1000.csv
contentment_2nd_1000.csv      sadness_2nd_1000.csv
contentment_3rd_1000.csv      sadness_3rd_1000.csv
contentment_4th_2000.csv      sadness_4th_2000.csv
contentment_5th_2000.csv      sadness_5th_2000.csv
contentment_6th_3000.csv      sadness_6th_3000.csv
disgust_1st_1000.csv

In [96]:
amusement_excitement_dfs = list()
for csv in DATASET_PATH.glob('amusement*'):
    print('File: ', csv)
    df = pd.read_csv(csv, names=['emotion', 'url', 'disagree', 'agree'])
    display(df.head(n=1))
    amusement_excitement_dfs.append(df)

for csv in DATASET_PATH.glob('excitement*'):
    print('File: ', csv)
    df = pd.read_csv(csv, names=['emotion', 'url', 'disagree', 'agree'])
    display(df.head(n=1))
    amusement_excitement_dfs.append(df)

File:  agg/amusement_1st_1000.csv

,emotion,url,disagree,agree
0,amusement,http://farm4.staticflickr.com/3935/15670302655...,5,0

File:  agg/amusement_1st_ins_1000.csv

,emotion,url,disagree,agree
0,amusement,http://cs.rochester.edu/u/qyou/Ins/Imgs/amusem...,0,5

File:  agg/amusement_2nd_1000.csv

,emotion,url,disagree,agree
0,amusement,http://farm8.staticflickr.com/7082/7270586204_...,3,2

File:  agg/amusement_3rd_1000.csv

,emotion,url,disagree,agree
0,amusement,http://farm3.staticflickr.com/2871/9271575365_...,1,4

File:  agg/amusement_4th_2000.csv

,emotion,url,disagree,agree
0,amusement,http://farm9.staticflickr.com/8293/7493279344_...,1,4

File:  agg/amusement_5th_2000.csv

,emotion,url,disagree,agree
0,amusement,http://farm9.staticflickr.com/8027/7595397962_...,4,1

File:  agg/amusement_6th_3000.csv

,emotion,url,disagree,agree
0,amusement,http://farm8.staticflickr.com/7192/6826900930_...,2,3

File:  agg/excitement_1st_1000.csv

,emotion,url,disagree,agree
0,excitement,http://farm8.staticflickr.com/7111/7551239746_...,3,2

File:  agg/excitement_1st_ins_1000.csv

,emotion,url,disagree,agree
0,excitement,http://cs.rochester.edu/u/qyou/Ins/Imgs/excite...,2,3

File:  agg/excitement_2nd_1000.csv

,emotion,url,disagree,agree
0,excitement,http://farm4.staticflickr.com/3723/13164215815...,4,1

File:  agg/excitement_3rd_1000.csv

,emotion,url,disagree,agree
0,excitement,http://farm9.staticflickr.com/8008/7367802022_...,1,4

File:  agg/excitement_4th_2000.csv

,emotion,url,disagree,agree
0,excitement,http://farm8.staticflickr.com/7373/12707836113...,4,1

File:  agg/excitement_5th_2000.csv

,emotion,url,disagree,agree
0,excitement,http://farm9.staticflickr.com/8506/8562547694_...,4,1

File:  agg/excitement_6th_3000.csv

,emotion,url,disagree,agree
0,excitement,http://farm6.staticflickr.com/5566/15030072670...,3,2

In [97]:
ae_df = pd.concat(amusement_excitement_dfs)

In [98]:
ae_df = ae_df.drop_duplicates(subset='url')

In [99]:
print(ae_df.shape)
ae_df.head()

(21932, 4)

,emotion,url,disagree,agree
0,amusement,http://farm4.staticflickr.com/3935/15670302655...,5,0
1,amusement,http://farm9.staticflickr.com/8519/8667561987_...,5,0
2,amusement,http://farm4.staticflickr.com/3802/9566768469_...,0,5
3,amusement,http://farm9.staticflickr.com/8231/8565444625_...,3,2
4,amusement,http://farm4.staticflickr.com/3736/9929371604_...,2,3

In [100]:
fear_sadness_dfs = list()
for csv in DATASET_PATH.glob('fear*'):
    print('File: ', csv)
    df = pd.read_csv(csv, names=['emotion', 'url', 'disagree', 'agree'])
    display(df.head(n=1))
    fear_sadness_dfs.append(df)

for csv in DATASET_PATH.glob('sadness*'):
    print('File: ', csv)
    df = pd.read_csv(csv, names=['emotion', 'url', 'disagree', 'agree'])
    display(df.head(n=1))
    fear_sadness_dfs.append(df)

File:  agg/fear_1st_1000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm9.staticflickr.com/8458/8000652950_...         4      1

File:  agg/fear_1st_ins_1000.csv

  emotion                                                url  disagree  agree
0    fear  http://cs.rochester.edu/u/qyou/Ins/Imgs/fear/1...         5      0

File:  agg/fear_2nd_1000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm6.staticflickr.com/5557/15002014032...         5      0

File:  agg/fear_3rd_1000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm6.staticflickr.com/5502/9838069254_...         5      0

File:  agg/fear_4th_2000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm9.staticflickr.com/8047/8134900740_...         5      0

File:  agg/fear_5th_2000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm9.staticflickr.com/8194/8106789131_...         3      2

File:  agg/fear_6th_3000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm4.staticflickr.com/3744/12688967253...         5      0

File:  agg/fear_7th_2000.csv

  emotion                                                url  disagree  agree
0    fear  http://farm6.staticflickr.com/5517/13938869280...         4      1

File:  agg/sadness_1st_1000.csv

   emotion                                                url  disagree  agree
0  sadness  http://farm4.staticflickr.com/3008/3077527460_...         5      0

File:  agg/sadness_1st_ins_1000.csv

   emotion                                                url  disagree  agree
0  sadness  http://cs.rochester.edu/u/qyou/Ins/Imgs/sadnes...         4      1

File:  agg/sadness_2nd_1000.csv

   emotion                                                url  disagree  agree
0  sadness  http://farm7.staticflickr.com/6019/6220568335_...         3      1

File:  agg/sadness_3rd_1000.csv

   emotion                                                url  disagree  agree
0  sadness  http://farm4.staticflickr.com/3935/15400827416...         5      0

File:  agg/sadness_4th_2000.csv

   emotion                                                url  disagree  agree
0  sadness  http://farm7.staticflickr.com/6187/6106628964_...         3      2

File:  agg/sadness_5th_2000.csv

   emotion                                                url  disagree  agree
0  sadness  http://farm6.staticflickr.com/5298/5587995211_...         2      3

File:  agg/sadness_6th_3000.csv

   emotion                                                url  disagree  agree
0  sadness  http://farm5.staticflickr.com/4128/4969051245_...         4      1

In [101]:
fs_df = pd.concat(fear_sadness_dfs)

In [102]:
fs_df.shape

(23866, 4)

In [103]:
fs_df = fs_df.drop_duplicates(subset='url')

In [104]:
print(fs_df.shape)
fs_df.head()

(23547, 4)

  emotion                                                url  disagree  agree
0    fear  http://farm9.staticflickr.com/8458/8000652950_...         4      1
1    fear  http://farm3.staticflickr.com/2912/14021657065...         5      0
2    fear  http://farm9.staticflickr.com/8433/7761626780_...         5      0
3    fear  http://farm3.staticflickr.com/2900/14803781093...         3      2
4    fear  http://farm4.staticflickr.com/3893/14516503964...         5      0

## Filter DFs

In [138]:
ae_df_filtered = ae_df[ae_df.agree > ae_df.disagree]

In [141]:
children = []
for i, row in ae_df_filtered.sample(5).iterrows():
    children.append(widgets.Image(value=bytes(row.url, 'utf-8'), format='url', width=256))
display(HBox(children=children))

HBox(children=(Image(value=b'http://farm6.staticflickr.com/5512/14061889199_218b2f40f1_z.jpg', format='url', w…

In [142]:
fs_df_filtered = fs_df[fs_df.agree > fs_df.disagree]

In [148]:
children = []
for i, row in fs_df_filtered.sample(5).iterrows():
    children.append(widgets.Image(value=bytes(row.url, 'utf-8'), format='url', width=256))
display(HBox(children=children))

HBox(children=(Image(value=b'http://farm8.staticflickr.com/7440/13938183903_7853bb039c_z.jpg', format='url', w…

In [149]:
ae_df_filtered.to_pickle('ae_df_filtered.pkl')

In [150]:
fs_df_filtered.to_pickle('fs_df_filtered.pkl')

## Train Test Split and Download Images

In [8]:
from sklearn.model_selection import train_test_split

In [27]:
from multiprocessing.pool import ThreadPool

In [9]:
ae_df_filtered = pd.read_pickle('ae_df_filtered.pkl')
fs_df_filtered = pd.read_pickle('fs_df_filtered.pkl')

In [10]:
ae_df_train, ae_df_test = train_test_split(ae_df_filtered, test_size=0.2)

In [11]:
ae_df_train.shape, ae_df_test.shape

((6268, 4), (1568, 4))

In [12]:
fs_df_train, fs_df_test = train_test_split(fs_df_filtered, test_size=0.2)

In [13]:
fs_df_train.shape, fs_df_test.shape

((3133, 4), (784, 4))

In [14]:
ae_df_train_sampled = ae_df_train.sample(frac=0.5)
ae_df_test_sampled = ae_df_test.sample(frac=0.5)

In [15]:
!mkdir -p train/positive
!mkdir -p train/negative

!mkdir -p test/positive
!mkdir -p test/negative

In [16]:
def download_image(url, folder):
    !wget -q {url} -P {folder}

In [ ]:
for i, row in tqdm_notebook(ae_df_train.iterrows()):
    !wget -q {row.url} -P train/positive/

/home/niharg/miniconda3/envs/magenta2/lib/python3.7/site-packages/ipykernel_launcher.py:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  """Entry point for launching an IPython kernel.

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

^C
^C
^C
^C
^C

In [28]:
pool = ThreadPool(processes=8)

In [31]:
def download_train_positive(args):
    i, row = args
    download_image(row.url, 'train/positive/')

In [32]:
pool.map(download_train_positive, ae_df_train_sampled.iterrows())

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

In [33]:
def download_train_negative(args):
    i, row = args
    download_image(row.url, 'train/negative/')

In [34]:
pool.map(download_train_negativeive, fs_df_train.iterrows())

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

In [35]:
def download_test_positive(args):
    i, row = args
    download_image(row.url, 'test/positive/')

In [40]:
pool2 = ThreadPool(processes=12)

In [42]:
_ = pool2.map(download_test_positive, ae_df_test_sampled.iterrows())

In [43]:
def download_test_negative(args):
    i, row = args
    download_image(row.url, 'test/negative/')

In [44]:
_ = pool2.map(download_test_negative, fs_df_test.iterrows())